spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.77.176.55:3306/meet?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    username: root
    password: root
  redis:
    host: 120.77.176.55
    port: 6379
  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 465
    username: 1452618379@qq.com
    password: tpdvwwqgafgwicae
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    from: 1452618379@qq.com
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
qiniu:
  accessKey: "SStPJbNpriAFEzb0LvB1ooO7X__CB5xpwt8cE8UE"
  secretKey: "aMbK1T32B4_Gidwm_zbFAVPmaBG2j-DgZkEQLEmT"
  bucket: "notehub"



